### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by d3rky** [dmitryikh/nla3d#2]
Please, add description to each class, field, property and function. Don't forget about function and constructor arguments. It is not easy to understand what function or class is used for without comments. And maybe you change directory structure? Separate headers and .cpp files, separate headers and .cpp files for third party libs, INSTALL text and other. Just google about it.

And another question. Why do you need your own realization of sparse matrix. I think there are thousands of such libs...

**Comment by dmitryikh** [comment]
Dear d3rky,

Thanks for your advice!

In today commit I massively added comments into FEStorage class. This class is a central place in nla3d and if you'd like to get familiar with nla3d you need to start with FEStorage class. Also, you can read in README.md about brief overview of the project (its capabilities and limitations).

I will think about separation cpp and hpp file. For now, I'm not sure that it helps to the project somehow.

About sparse matrices. I used MKL to solve large linear systems of equations, and MKL (PARDISO part) needs to work with a particular type of storage of sparse matrices. I just write a wrapper of this kind of storage. Another reason is educational one. It was interesting to implement it by myself.

**Comment by dmitryikh** [comment]
And of course I will continue to work anded README and INSTALLATION files in order to get it easy for someone to get involved into the project.  I will be glad to see you comments in future!

**Comment by d3rky** [comment]
Thanks. I'll pull it and see code and try to understand how it works. And what about the future? Maybe you can write about your plans to lonkin.p.v@gmail.com and close this issue. Можно по русски :-)
